export const colorList: Array<string> = [
  "",
	"cyan",
  "cyanbg",
  "cyangroup",
  "purple",
  "purplebg",
  "purplegroup",
  "yellow",
  "yellowbg",
  "yellowgroup",
  "black",
  "blackbg",
  "blackgroup",
  "mw_red",
  "mw_redbg",
  "mw_redgroup",
  "mw_pink",
  "mw_pinkbg",
  "mw_pinkgroup",
  "mw_purple",
  "mw_purplebg",
  "mw_purplegroup",
  "mw_deep_purple",
  "mw_deep_purplebg",
  "mw_deep_purple",
  "mw_indigo",
  "mw_indigobg",
  "indigogroup",
  "mw_blue",
  "mw_bluebg",
  "mw_bluegroup",
  "mw_light_blue",
  "mw_light_bluebg",
  "mw_light_bluegroup",
  "mw_cyan",
  "mw_cyanbg",
  "mw_cyangroup",
  "mw_teal",
  "mw_tealbg",
  "mw_tealgroup",
  "mw_green",
  "mw_greenbg",
  "mw_greengroup",
  "mw_light_green",
  "mw_lightgreenbg",
  "mw_lightgreengroup",
  "mw_lime",
  "mw_limebg",
  "mw_limegroup",
  "mw_yellow",
  "mw_yellowbg",
  "mw_yellowgroup",
  "mw_amber",
  "mw_amberbg",
  "mw_ambergroup",
  "mw_orange",
  "mw_orangebg",
  "mw_orangegroup",
  "mw_deep_orange",
  "mw_deep_orangebg",
  "mw_deep_orangegroup",
  "mw_brown",
  "mw_brownbg",
  "mw_browngroup",
  "mw_gray",
  "mw_graybg",
  "mw_graygroup",
  "mw_blue_gray",
  "mw_blue_graybg",
  "mw_blue_graygroup",
];

export const colorMap: Record<string, string> = {
  "": "",
  cyan: "#233",
  cyanbg: "#355",
  cyangroup: "#8AA", 
  purple: "#323",
  purplebg: "#535",
  purplegroup: "#a1309b", 
  yellow: "#432",
  yellowbg: "#653",
  yellowgroup: "#b58b2a", 
  black: "#222",
  blackbg: "#000",
  blackgroup: "#444", 
  mw_red: "#962123",
  mw_redbg: "#B71C1C",
  mw_redgroup: "#FF595C", 
  mw_pink: "#792243",
  mw_pinkbg: "#880E4F",
  mw_pinkgroup: "#FF5984", 
  mw_purple: "#42137E",
  mw_purplebg: "#4A148C",
  mw_purplegroup: "#FF5EAF", 
  mw_deep_purple: "#291983",
  mw_deep_purplebg: "#311B92",
  mw_deep_purplegroup: "#FF63BE", 
  mw_indigo: "#132270",
  mw_indigobg: "#1A237E",
  indigogroup: "#FF68D3", 
  mw_blue: "#063B94",
  mw_bluebg: "#0D47A1",
  mw_bluegroup: "#FF6EFF", 
  mw_light_blue: "#004B8E",
  mw_light_bluebg: "#01579B",
  mw_light_bluegroup: "#FF7AFF", 
  mw_cyan: "#005658",
  mw_cyanbg: "#006064",
  mw_cyangroup: "#00FF9E", 
  mw_teal: "#004333",
  mw_tealbg: "#004D40",
  mw_tealgroup: "#00FFB9", 
  mw_green: "#145013",
  mw_greenbg: "#1B5E20",
  mw_greengroup: "#FF6F5C", 
  mw_light_green: "#2C5F11",
  mw_lightgreenbg: "#33691E",
  mw_lightgreengroup: "#FF8259", 
  mw_lime: "#766B0A",
  mw_limebg: "#827717",
  mw_limegroup: "#FFD14B", 
  mw_yellow: "#EE740A",
  mw_yellowbg: "#F57F17",
  mw_yellowgroup: "#FFFF4B", 
  mw_amber: "#F96200",
  mw_amberbg: "#FF6F00",
  mw_ambergroup: "#FFA334", 
  mw_orange: "#D94700",
  mw_orangebg: "#E65100",
  mw_orangegroup: "#FF7234", 
  mw_deep_orange: "#B52C00",
  mw_deep_orangebg: "#BF360C",
  mw_deep_orangegroup: "#FF5733", 
  mw_brown: "#371D1A",
  mw_brownbg: "#3E2723",
  mw_browngroup: "#A1807B", 
  mw_gray: "#1A1717",
  mw_graybg: "#212121",
  mw_graygroup: "#848282", 
  mw_blue_gray: "#1F2F30",
  mw_blue_graybg: "#263238",
  mw_blue_graygroup: "#6F9FA0",
};

export const ColorMenu = colorList.map((c: string, i: number) => ({
  label: (
    <div
      style={{
        background: colorMap[c] || "#eee",
        width: 16,
        height: 16,
        borderRadius: "50%",
      }}
    />
  ),
  name: c,
  key: i,
}));
